name: Deploy Azure Infrastructure

on:
  workflow_call:
    inputs:
      environment:
        description: 'Environment to deploy to'
        required: true
        type: string
    secrets:
      AZURE_CREDENTIALS:
        required: true
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy to'
        required: true
        default: 'Dev'
        type: choice
        options:
        - Dev
        - Staging
        - Production

jobs:
  deploy_infrastructure:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy Bicep file
        uses: azure/cli@v2
        with:
          inlineScript: |
            az deployment sub create \
              --location australiaeast \
              --template-file ./azure/main.bicep \
              --parameters environment=${{ inputs.environment }} \
              --verbose