name: Deploy Azure Infrastructure

on:
  workflow_dispatch:

jobs:
  deploy_dev:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy Bicep file
        uses: azure/cli@v2
        with:
          inlineScript: |
            az deployment sub create \
              --template-file ./azure/main.bicep \
              --parameters ./azure/dev_parameters.json