name: Main Workflow

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy to'
        required: true
        default: 'Dev'
        type: choice
        options:
        - Dev
        - Staging
        - Production

jobs:
  infra:
    uses: ./.github/workflows/infra.yml
    with:
      environment: ${{ inputs.environment }}
    secrets:
      AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}

  build_api:
    needs: infra
    uses: ./.github/workflows/build-api.yml

  deploy_api:
    needs: build_api
    uses: ./.github/workflows/deploy-api.yml
    with:
      environment: ${{ inputs.environment }}
    secrets:
      AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}